name: Fix README

on:
  push:
    paths: 
      - .github/workflows/main.yml
      - README.md
  workflow_dispatch:
  schedule:
    #        ┌──────────────── minute (0 - 59)
    #        │ ┌────────────── hour (0 - 23)
    #        │ │ ┌──────────── day of the month (1 - 31)
    #        │ │ │ ┌────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌──────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 0 * * MON-FRI'

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Fix README
        env:
          IMAGE_NAME: '![Ting Ying](resources/image.jpeg)'
        run: |
          grep -F "$IMAGE_NAME" README.md || echo "$IMAGE_NAME" >> README.md
          git add README.md
          git commit -m "docs: return README to its rightful state" || true
          git push
